### ISSUE TITLE
New version of run_eggla_gwas not working

### ISSUE THREAD

**Issue by annihei** [mcanouil/eggla#107] opened 2023-04-11 11:41 UTC
### Bug description

Hi Mickael, I have been trying to run GWASes again with the new version and I am running out o ideas what to do. When I try the gwas with all four types of phenotypre, the analysis stops at chromosome 4:
```
run_eggla_gwas(
  data = pcs,
  results = res,
  id_column ="ID",
  traits = c("slope_.*", "auc_.*", "^AP_.*", "^AR_.*"),
  covariates = c("sex","PC1", "PC2", "PC3", "PC4", "PC5"),
  vcfs = list.files(
      path = "/.../genetic_files/",
      pattern = "\\.vcf$|\\.vcf.gz$",
      full.names = TRUE
    ),
  working_directory = "/wrk/anni/",
  use_info = TRUE,
  bin_path = list(bcftools = "/usr/local/bin/bcftools",plink2 = "/usr/local/bin/plink2"),
  bcftools_view_options = NULL,
  build = "37",
  strand = "+",
  info_type = "minimac3 R2",
  threads = 1,
  quiet = FALSE,
  clean = TRUE
)
...
...
...
[chr3.dose.vcf.gz] Performing PLINK2 regression ...
[chr3.dose.vcf.gz] Combining results files ...
[chr3.dose.vcf.gz] Extracting INFO ...
[chr3.dose.vcf.gz] Computing PLINK2 missing rate ...
[chr3.dose.vcf.gz] Computing PLINK2 Hardy-Weinberg test ...
[chr3.dose.vcf.gz] Results written in "/.../gwas_plink2/da9ed3b2a26386f9bbc14160926d590a__chr3.dose.results.gz"
[chr4.dose.vcf.gz] Performing PLINK2 regression ...
[chr4.dose.vcf.gz] Combining results files ...
Error in data.table::setnames(x = results, old = c("CHROM", "POS", "ID",  :
  Items of 'old' not found in column names: [CHROM, POS, ID, A1, AX, A1_FREQ, MACH_R2, OBS_CT, BETA, SE, ...]. Consider skip_absent=TRUE.
In addition: Warning message:
In `[.data.table`(data.table::setnames(x = data.table::rbindlist(l = lapply(X = (function(x) `names<-`(x,  :
  column(s) not removed because not found: [TEST, T_STAT, REF, ALT]
```
I tried running the analysis only with chromosome 4 and that got completed without problems. 

I also tried the GWAS with only AUC and slope as didn't have any problems with the same data sets in the previous version of eggla that I used (I have only been running the analyses with slope and auc until now), and with this got an error at chromosome 6:
```
run_eggla_gwas(
  data = pcs,
  results = res,
  id_column ="ID",
  traits = c("slope_.*", "auc_.*"),
  covariates = c("sex","PC1", "PC2", "PC3", "PC4", "PC5"),
  vcfs = list.files(
      path = "/.../genetic_files/",
      pattern = "\\.vcf$|\\.vcf.gz$",
      full.names = TRUE
    ),
  working_directory = "/wrk/anni/",
  use_info = TRUE,
  bin_path = list(bcftools = "/usr/local/bin/bcftools",plink2 = "/usr/local/bin/plink2"),
  bcftools_view_options = NULL,
  build = "37",
  strand = "+",
  info_type = "minimac3 R2",
  threads = 1,
  quiet = FALSE,
  clean = TRUE
)
[chr5.dose.vcf.gz] Results written in "/.../gwas_plink2/afdae49888058df51fdaf6dcb37c4c28__chr5.dose.results.gz"
[chr6.dose.vcf.gz] Performing PLINK2 regression ...
[chr6.dose.vcf.gz] Combining results files ...
[chr6.dose.vcf.gz] Extracting INFO ...
[chr6.dose.vcf.gz] Computing PLINK2 missing rate ...
[chr6.dose.vcf.gz] Computing PLINK2 Hardy-Weinberg test ...
Error in data.table::fread(sprintf("%s.vmiss", results_file)) :
  File '/.../gwas_plink2/afdae49888058df51fdaf6dcb37c4c28__chr6.dose.vmiss' does not exist or is non-readable. getwd()=='/wrk/anni/'
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<6     87575956        6:87575956:A:T  A       T       T       A       1827.>>
2: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<6     87576217        6:87576217:G:T  G       T       T       G       420.028 7226    0.0581274       0.98993 PC3     3613    -0.0119956      0.00827245      -1.45007        0.14712>>
3: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<6     87574674        6:87574674:A:G  A       G       G       A       0.0418091       7226    5.785>>
4: In FUN(X[[i]], ...) : Discarded single-line footer: <<6      87571928        6:8>>
5: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<6     87575584        6:87575584:G:A  G       A       A       G       0.0310059       7226    4.29087e-06     0.0309974       PC2     3>>
6: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<6     87576714        6:87576714:G:A  G       A       A       G       0.00292969      7226    4.05437e-07     0.000975752     PC2     3613    0.00012>>
>
```
What do you think of this?

### `eggla` version output

```
> packageVersion('eggla')
[1] ‘0.19.0’
```

### Checklist

- [X] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?
- [X] included a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] documented the version of `eggla` you're running, by pasting the output from running `packageVersion('eggla')` in the "`eggla` version output" text area?
- [X] documented which operating system you're running? If on Linux, please provide the specific distribution as well.

**Comment by mcanouil** [comment] 2023-04-11 12:33
Could you run the function with `clean = FALSE`, and look at one results file in `/wrk/anni`, especially the columns you have.
The issue arise at the following lines changed in #97, but I did not have any issues in my tests:
https://github.com/mcanouil/eggla/blob/75144ee87242378d3dbd8d2dee4119c42dffc71f/R/run_eggla_gwas.R#L510-L538

**Comment by annihei** [comment] 2023-04-12 11:42
Of course, I will update when I get some results with clean=FALSE. 

As far as I know @burrowsk has tested it with ALSPAC, I understood that was fine?

**Comment by mcanouil** [comment] 2023-04-13 12:07
@annihei FWI, you don't need to run the GWAS for all chromosomes or on all individuals.
I think the issue is simple about your VCF files, which might not contain what @burrowsk and I have (if I recall properly, you do not have the same imputation metrics for instance).

**Comment by annihei** [comment] 2023-04-14 07:45
I think it is strange that the issue occurs in a different chromosome every time. Here's now the latest result, in the command I had all traits included as in the first command shown in the above comment (that time it had gone through more chromosomes than now):
```
run_eggla_gwas(
  data = pcs,
  results = res,
  id_column ="ID",
  traits = c("slope_.*", "auc_.*", "^AP_.*", "^AR_.*"),
  covariates = c("sex","PC1", "PC2", "PC3", "PC4", "PC5"),
  vcfs = list.files(
      path = "/.../genetic_files/",
      pattern = "\\.vcf$|\\.vcf.gz$",
      full.names = TRUE
    ),
  working_directory = "/wrk/anni/",
  use_info = TRUE,
  bin_path = list(bcftools = "/usr/local/bin/bcftools",plink2 = "/usr/local/bin/plink2"),
  bcftools_view_options = NULL,
  build = "37",
  strand = "+",
  info_type = "minimac3 R2",
  threads = 1,
  quiet = FALSE,
  clean = FALSE
)
...
....
....
[chr2.dose.vcf.gz] Results written in "/.../gwas_plink2/d73503fc0464566816b7f320358a6391__chr2.dose.results.gz"
[chr20.dose.vcf.gz] Performing PLINK2 regression ...
[chr20.dose.vcf.gz] Combining results files ...
[chr20.dose.vcf.gz] Extracting INFO ...
[chr20.dose.vcf.gz] Computing PLINK2 missing rate ...
[chr20.dose.vcf.gz] Computing PLINK2 Hardy-Weinberg test ...
Error in data.table::fread(sprintf("%s.vmiss", results_file)) :
  File '/.../gwas_plink2/d73503fc0464566816b7f320358a6391__chr20.dose.vmiss' does not exist or is non-readable. getwd()=='/wrk/anni/'
In addition: There were 11 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41158156        20:41158156:T:C T       C       C       T       2728.41 7158    0.38117 0.998252        PC>>
2: In FUN(X[[i]], ...) : Discarded single-line footer: <<2>>
3: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41155126        20:41155126:A:T A       T       T       A       7.43195 7158    0.00103827      0.7747  PC3>>
4: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41154033        20:41154033:C:T C       T       T       C       52.8987 7158    0.00739015      0.924387        PC2     3579    1.54572e-05     0.0175046     0.00>>
5: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41150971        20:41150971:T:G T       G       G       T       0       7158    0       n>>
6: In FUN(X[[i]], ...) : Discarded single-line footer: <<20     41154162>>
7: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41156384        20:41156384:T:A T       A       A       T       0.23999 715>>
8: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41148313        20:41148313:T:A T       A       A       T       4.75684 7158    0.0>>
9: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41152302        20:41152302:G:A G       A       A       G       3.02502 7158    0.00042>>
10: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41156241        20:41156241:A:C A>>
11: In FUN(X[[i]], ...) :
  Discarded single-line footer: <<20    41157181        20:41157181:T:C T       C       C       T       27.1082 7158    0.00378712      0.929206        PC3     3579    -0.000134311    0.000176839   -0.759515       0.>>
```
When I compare the files in .../gwas_plink2/ file between chr2 and chr20, they have the same files except these:
only chr2:
d73503fc0464566816b7f320358a6391__chr2.dose.hardy
d73503fc0464566816b7f320358a6391__chr2.dose.smiss
d73503fc0464566816b7f320358a6391__chr2.dose.vmiss
d73503fc0464566816b7f320358a6391__chr2.dose.results.gz

only chr20:
d73503fc0464566816b7f320358a6391__chr20.dose-temporary.pgen
d73503fc0464566816b7f320358a6391__chr20.dose-temporary.psam
d73503fc0464566816b7f320358a6391__chr20.dose-temporary.pvar.zst

**Comment by burrowsk** [comment] 2023-04-14 07:56
Hi @annihei What happens if you only run one set of traits e.g. "slope_.*" on a couple of chromosomes (e.g. 21 & 22 for quickness; you can just move the other chromosome files to a subdirectory so they are not included in the analysis). When I ran the new code on our servers there were memory issues, even when I use entire high memory nodes, so I had to run the traits in three separate runs. I also ran the chromosomes in parallel 6 at a time as running all 22 in parallel would sometimes cause memory issues too.

**Comment by mcanouil** [comment] 2023-04-14 08:11
I think it might be that PLINK2 ran out of memory thus failing to compute the "statistics" files.
But without profiling the job for memory issues, I can't really tell.

Note that your last run failed at https://github.com/mcanouil/eggla/blob/75144ee87242378d3dbd8d2dee4119c42dffc71f/R/run_eggla_gwas.R#L599-L608

I went back to PLINK2 website and the issue might be with PLINK2 itself.
I am completely sure, that's the issue, but the bugs fixed here seems highly related to both of your issues @burrowsk and @annihei 
Could you try to update your PLINK2 version?
Internally `eggla` uses the 9th of January version, version just before the three bugs were fixed.
<img width="456" alt="image" src="https://user-images.githubusercontent.com/8896044/231984910-c864e776-60ea-4af8-b02a-19c6e0911e97.png">

> 29 Mar: Fixed a rare multiallelic-variant .pgen writing bug that could result in an obviously-corrupted .pgen ([--validate](https://www.cog-genomics.org/plink/2.0/other#validate) reports unexpected file size) when REF and ALT1 frequencies are both low.
> 25 Mar: Fixed [--indep-pairwise](https://www.cog-genomics.org/plink/2.0/ld#indep) chrX bug that occurred when some nonfounders were present. --indep-pairwise speed improvement. --indep-order flag added; "--indep-order 2" greatly speeds up --indep-pairwise while slightly changing results, and will become the default in the future. [--glm](https://www.cog-genomics.org/plink/2.0/assoc#glm) 'provref' optional column set added, distinguishing provisional from known reference alleles; this will be included in the default column set in the future.
> 3 Mar: Fixed --hardy/--hwe bug that could cause a segfault when chrX and multiallelic variants are present, and sex information is absent. [--glm](https://www.cog-genomics.org/plink/2.0/assoc#glm) 'omitted' optional column set added, listing only the omitted allele; this (and 'a1freq') will be included in the default column set in the future. --glm 'ax' column set deprecated. Linux builds now avoid requesting more memory than reported by /proc/meminfo's 'MemAvailable' entry (when it exists). --pca now prints a more informative error message when there is a nan in the GRM.

**Comment by mcanouil** [comment] 2023-04-14 14:17
I just released v0.19.2 (see <https://github.com/mcanouil/eggla/releases/tag/v0.19.2>).
Continuous Integration checks and Docker image build are ongoing.

Let me know, if the issue was really about the segfault in PLINK2.

**Comment by annihei** [comment] 2023-04-24 08:35
I managed to analyse the slopes and all chromosomes on one go after the update (didn't try with all phenotypes). I got following warnings:
```
Warning: --glm 'ax' column is deprecated; you probably want 'omitted' instead.
If you think you need ax's current behavior, contact the developers and
describe your use case.
```
I'll go through the results with more detail this week as this was the first time I managed to get results after the updates.

gwas-software.txt is missing the plink2 and bcftools versions:
```
$ cat gwas-software.txt
R version 4.2.2 Patched (2022-11-10 r83330)
```

**Comment by annihei** [comment] 2023-04-24 09:41
Here is my command:
```
run_eggla_gwas(
  data = pcs,
  results = res,
  id_column ="ID",
  traits = c("slope_.*"),
  covariates = c("sex","PC1", "PC2", "PC3", "PC4", "PC5"),
  vcfs = list.files(
      path = "/.../genetic_files/",
      pattern = "\\.vcf$|\\.vcf.gz$",
      full.names = TRUE
    ),
  working_directory = "/.../nfbc1966",
  use_info = TRUE,
  bin_path = list(bcftools = "/usr/local/bin/bcftools",plink2 = "/usr/local/bin/plink2"),
  bcftools_view_options = NULL,
  build = "37",
  strand = "+",
  info_type = "minimac3 R2",
  threads = 1,
  quiet = FALSE,
  clean = FALSE
)
```
And here's for plink and bcftools:
```
> bin_path = list(bcftools = "/usr/local/bin/bcftools",plink2 = "/usr/local/bin/plink2")
>  plink_version <- try(
+    expr = system(
     ignore.stdout = TRUE,
     ignore.stderr = TRUE
+      command = sprintf("%s --version", bin_path[["plink2"]]),
+      intern = TRUE,
+      ignore.stdout = TRUE,
+      ignore.stderr = TRUE
+    ),
+    silent = TRUE
+  )

>  if (inherits(plink_version, "try-error") || !file.exists(bin_path[["plink2"]])) {
+    stop("Please check PLINK2 binary path!")
+  }
> plink_version
character(0)

> bcftools_version <- try(
+    expr = system(
+      command = sprintf("%s --version", bin_path[["bcftools"]]),
+      intern = TRUE,
+      ignore.stdout = TRUE,
+      ignore.stderr = TRUE
+    ),
+    silent = TRUE
+  )
>  if (inherits(bcftools_version, "try-error") || !file.exists(bin_path[["bcftools"]])) {
+    stop("Please check BCFTools binary path!")
+  }
> bcftools_version
character(0)
```
Plink should be fine :
```
$ /usr/local/bin/plink2
PLINK v2.00a4LM AVX2 Intel (11 Apr 2023)       www.cog-genomics.org/plink/2.0/
(C) 2005-2023 Shaun Purcell, Christopher Chang   GNU General Public License v3
...
...
...

$ /usr/local/bin/bcftools

Program: bcftools (Tools for variant calling and manipulating VCFs and BCFs)
Version: 1.10.2 (using htslib 1.10.2)

Usage:   bcftools [--version|--version-only] [--help] <command> <argument>
...
...
...
```

**Comment by mcanouil** [comment] 2023-04-24 19:35
@annihei Thanks, for these detailed output. I was able to reproduce both issue: version not being printed in the file and the new warning from PLINK2 GLM.
A fixe is coming in #109

**Comment by mcanouil** [comment] 2023-04-24 20:46
I am building the new version.
Feel free to re-open if it is really fixed in your setup.

**Closed** 2023-04-24 20:45 UTC
Labels: bug, dependencies

**Comment by annihei** [comment] 2023-04-27 12:10
I tried just with slopes and 2 chromosomes and both issues were fixed, thank you!

**Comment by burrowsk** [comment] 2023-04-27 12:33
> I tried just with slopes and 2 chromosomes and both issues were fixed, thank you!

And I've just ran it on all phenos and chromosome 21 in ALSPAC with no issues. 
Now to run on everything :)

Thanks both!
